#!/usr/bin/env bash
# Configure domain zone so that the subdomain www points to load-balancer IP

func () {
	var=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $var" | awk '{print "The subdomain " $1 " is a " $2 " record and points to "$3}'
}

if [ "$#" -eq 2 ]
then
	func "$1" "$2"
else
	func "$1" 'www'
	func "$1" 'lb-01'
	func "$1" 'web-01'
	func "$1" 'web-02'
fi
