#!/usr/bin/env bash
# Bash that loops from 1 to 10 and displays
# "bad luck" at 4th iteration
# "good luck" at 8th iteration
# "best school" for the rest

a=0
while [ $a -lt 10 ]
do
  if [ $a -eq 3 ]
  then
    echo "bad luck"
  elif [ $a -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( a++ ))
done
