#!/usr/bin/env bash
# Bash that loops from 1 to 20 and displays
# 4 and then bad luck from China at 4th iteration
# 9 and then bad luck from Japan at 9th iteration
# 17 and then bad luck from Italy at 17th iteration

a=1
while [ $a -le 20 ]
do
  echo "$a"
  case $a in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( a++ ))
done
